### ISSUE TITLE
Logo is not a link

### ISSUE THREAD

**Issue by willish** [Hitchwiki/HitchwikiVector-extension#1]
It seems the `p-logo` anchor element is not used properly. But cant figure out what is going on

I think the background image should be set on the `p-logo a` not `p-logo`. e.g:

    #p-logo {	
	position: fixed;
	top: 0;
	border-bottom: 1px solid @hw-orange-border;
	height: @header-height;

	// Original icon was here
	// Consider removing image with JS so we could keep the link?
	a {
		.background-image('images/hitchwiki-logo.png');
		background-position: center top;
		background-repeat: no-repeat;
		height: @header-height;
	}
}

But then the scrolling behaviour is strange. One also needs to set

    .mw-scrolled {
      #p-logo a{
  	    background-size: ......;
      }
    }

**Comment by simison** [comment]
You're right. Background should be set to `<a>` and `<a>` needs `text-indent:-9999px;` so that we won't have text floating on top of it.

**Comment by simison** [comment]
Tried to fix this. Turns out the Vector template includes HW L
